### ISSUE TITLE
Termux menu not working

### ISSUE THREAD

**Issue by Dream017** [CRANKV2/STRPxPUBG#3]
I installed it in magisk it was installed successfully but it's showing this in termux"▌Please Flash STRPxPUBG Module If You Want To Use This Menu

▌You Can Find It In Ur Group!"
![Screenshot_20240820-135017_Termux](https://github.com/user-attachments/assets/74d72f2e-b980-45da-9fc7-62db0fae5e96)

**Comment by CRANKV2** [comment]
This module is no longer available officially from our STRP Server.

Means, no matter where u have Downloaded this Module from, it is no longer Developed by me so there is no more Support or help for it. (since over 1 Year now)

## Instead, join our official group.
- https://t.me/AndroidRootModulesCommunity

and  Download ```STRP x PureGaming```

## Which includes:
- PG Module (for Magisk)
- PG APK (To control Stock & Gaming profiles without Termux.)

Thanks✓
